### ISSUE TITLE
Yahoo finance.keystats is broken

### ISSUE THREAD

**Issue by altamont** [yql/yql-tables#447]
yahoo.finance.keystats just returns the symbol.  The old xpath is:

var keystatsquery = y.xpath(
                                    rawresult,
                                    "//table[@class='yfnc_datamodoutline1']/tr/td/table/tr" +
                                    "/td[@class='yfnc_tabledata1' or @class='yfnc_tablehead1']"
                                );	

I think it needs to be changed to:
var keystatsquery = y.xpath(
                                    rawresult,
                                    "//table[@class='yfnc_datamodoutline1']/tbody/tr/td/table/tbody/tr" +
                                    "/td[@class='yfnc_tabledata1' or @class='yfnc_tablehead1']"
                                );

it looks like there are tbody tags that are throwing it off.  i haven't contributed to this project yet, and so i'm a little hesitant to make the change myself.  can someone comment as to whether they agree with this?

**Comment by TMcClain5** [comment]
I agree with you I believe that should fix the issue. The new <tbody> tag has to be what is throwing off all of the keystats queries.

**Comment by berndsi** [comment]
+1 I've made similar changes and more to another file (analystestimates) in [PR 499](https://phabricator.wikimedia.org/project/board/489/).

**Comment by tomasteicher** [comment]
I tried to run YQL query to table "Yahoo finance.keystats" but it still returns only symbols. If I understnad correctly, I need to use Xpath, and not such YQL selects?
I tried:
SELECT * FROM yahoo.finance.keystats WHERE symbol in ("N4E.SI","BS6.SI", "YHOO")
using env value: https://raw.githubusercontent.com/cynwoody/yql-tables/finance-1/tables.env

**Comment by BobAleena** [comment]
anyone get this working? I'm still getting back only symbols. Yahoo console keeps giving me a connect failure when i try it there too.

**Comment by fho** [comment]
Still broken would be awesome if something would get it fixed

**Comment by florent522** [comment]
Any update?

**Comment by BobAleena** [comment]
Nope - still broken for me. I tried @johnmwilson82's fix from above, but not working for me still
